{
 "title": "COVID and Unemployment Rate By Region",
 "description": "Presentation of COVID19 and its Effects on US Unemployment Rate",
 "time": { "from": "2019-12-01", "to": "2022-10-01" },
 "templating": {
  "list": [
   { "name": "Gender", "query": "Men, Women" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">COVID-19 and Unemployment Rate By Region </h1>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Western Region",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for different regions of the US at the peak periods of different COVID variants in comparison to the pre-COVID rate. Has COVID disproportionately affected a certain region in terms of employment?",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.WUR1 AS Pre_COVID,\n       urate.WUR2 AS WildType_Peak, \n \t   urate.WUR3 AS Alpha_Peak, \n \t   urate.WUR4 AS Delta_Peak,\n \t   urate.WUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.West ELSE 0 END) WUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.West ELSE 0 END) WUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.West ELSE 0 END) WUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.West ELSE 0 END) WUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.West ELSE 0 END) WUR5\n    FROM UnempRateRegionCol u, MinWestUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Western Region",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by region to trends in COVID cases by region over all relevant dates",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 2 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT Date, West\nFROM UnempRateRegionCol"
    },
    {
     "rawSql": "SELECT MonthDate, Cases_West\nFROM COVIDCasesMonthlyRegionCol"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Southern Region",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by region to trends in COVID cases by region over all relevant dates",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT Date, South\nFROM UnempRateRegionCol"
    },
    {
     "rawSql": "SELECT MonthDate, Cases_South\nFROM COVIDCasesMonthlyRegionCol"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Southern Region",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for the Southern region of the US at the peak periods of different COVID variants in comparison to the pre-COVID rate.",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.SUR1 AS Pre_COVID,\n       urate.SUR2 AS WildType_Peak, \n \t   urate.SUR3 AS Alpha_Peak, \n \t   urate.SUR4 AS Delta_Peak,\n \t   urate.SUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.South ELSE 0 END) SUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.South ELSE 0 END) SUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.South ELSE 0 END) SUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.South ELSE 0 END) SUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.South ELSE 0 END) SUR5\n    FROM UnempRateRegionCol u, MinSouthUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Northeast Region",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for the Northeastern region of the US at the peak periods of different COVID variants in comparison to the pre-COVID rate.",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.NEUR1 AS Pre_COVID,\n       urate.NEUR2 AS WildType_Peak, \n \t   urate.NEUR3 AS Alpha_Peak, \n \t   urate.NEUR4 AS Delta_Peak,\n \t   urate.NEUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.Northeast ELSE 0 END) NEUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.Northeast ELSE 0 END) NEUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.Northeast ELSE 0 END) NEUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.Northeast ELSE 0 END) NEUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.Northeast ELSE 0 END) NEUR5\n    FROM UnempRateRegionCol u, MinNortheastUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Northeastern Region",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by region to trends in COVID cases by region over all relevant dates",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 24 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT Date, Northeast\nFROM UnempRateRegionCol"
    },
    {
     "rawSql": "SELECT MonthDate, Cases_Northeast\nFROM COVIDCasesMonthlyRegionCol"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Midwestern Region",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by region to trends in COVID cases by region over all relevant dates",
   "gridPos": { "h": 11, "w": 15, "x": 0, "y": 35 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT Date, Midwest\nFROM UnempRateRegionCol"
    },
    {
     "rawSql": "SELECT MonthDate, Cases_Midwest\nFROM COVIDCasesMonthlyRegionCol"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Midwest",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for the Midwestern region of the US at the peak periods of different COVID variants in comparison to the pre-COVID rate.",
   "gridPos": { "h": 11, "w": 9, "x": 15, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.MWUR1 AS Pre_COVID,\n       urate.MWUR2 AS WildType_Peak, \n \t   urate.MWUR3 AS Alpha_Peak, \n \t   urate.MWUR4 AS Delta_Peak,\n \t   urate.MWUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.Midwest ELSE 0 END) MWUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.Midwest ELSE 0 END) MWUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.Midwest ELSE 0 END) MWUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.Midwest ELSE 0 END) MWUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.Midwest ELSE 0 END) MWUR5\n    FROM UnempRateRegionCol u, MinMidwestUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate By Region",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by region over all relevant dates",
   "gridPos": { "h": 11, "w": 21, "x": 1, "y": 46 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT Date, West, South, Northeast, Midwest\nFROM UnempRateRegionCol"
    }
   ]
  },
  {
   "title": "COVID Cases By Region",
   "type": "barchart",
   "description": "Compare trends in COVID cases by region over all relevant dates",
   "gridPos": { "h": 13, "w": 21, "x": 1, "y": 57 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT r.MonthDate, r.Cases_West, r.Cases_South, r.Cases_Northeast, r.Cases_Midwest\nFROM COVIDCasesMonthlyRegionCol r"
    }
   ]
  },
  {
   "title": "COVID Cases By Region",
   "type": "timeseries",
   "description": "Compare trends in COVID cases by region over all relevant dates",
   "gridPos": { "h": 12, "w": 21, "x": 1, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT MonthDate, Cases_West, Cases_South, Cases_Northeast, Cases_Midwest\nFROM COVIDCasesMonthlyRegionCol"
    }
   ]
  }
 ]
}