{
 "title": "COVID and Unemployment Rate By Gender",
 "description": "Presentation of COVID19 and its Effects on US Unemployment Rate",
 "time": { "from": "2019-12-01", "to": "2021-12-01" },
 "templating": {
  "list": [
   { "name": "Gender", "query": "Men, Women" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">COVID-19 and Unemployment Rate By Gender </h1>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Men",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for men and women over 20 years of age at the peak periods of different COVID variants in comparison to the pre-COVID rate, defined as December 2019. Has COVID disproportionately affected a gender group in terms of unemployment?",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.WUR1 AS Pre_COVID,\n       urate.WUR2 AS WildType_Peak, \n \t   urate.WUR3 AS Alpha_Peak, \n \t   urate.WUR4 AS Delta_Peak,\n \t   urate.WUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.Women_20_plus ELSE 0 END) WUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.Women_20_plus ELSE 0 END) WUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.Women_20_plus ELSE 0 END) WUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.Women_20_plus ELSE 0 END) WUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.Women_20_plus ELSE 0 END) WUR5\n    FROM Unemployment_Rate u, MinWomenUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Men ",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by gender to trends in COVID cases by gender over all relevant dates",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 2 },
   "targets": [
    {
     "rawSql": "SELECT u.Date, u.Men_20_plus\nFROM Unemployment_Rate u;"
    },
    {
     "rawSql": "SELECT g.MonthDate, g.Cases_Male\nFROM COVID_Cases_By_Gender_Monthly g;"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Women",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by gender to trends in COVID cases by gender over all relevant dates",
   "gridPos": { "h": 12, "w": 15, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT u.Date, u.Women_20_plus\nFROM Unemployment_Rate u"
    },
    {
     "rawSql": "SELECT g.MonthDate, g.Cases_Female \nFROM COVID_Cases_By_Gender_Monthly g"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Women",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for men and women over 20 years of age at the peak periods of different COVID variants in comparison to the pre-COVID rate, defined as December 2019. Has COVID disproportionately affected a gender group in terms of unemployment?",
   "gridPos": { "h": 12, "w": 9, "x": 15, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.MUR1 AS Pre_COVID,\n       urate.MUR2 AS WildType_Peak, \n \t   urate.MUR3 AS Alpha_Peak, \n \t   urate.MUR4 AS Delta_Peak,\n \t   urate.MUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.Men_20_plus ELSE 0 END) MUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.Men_20_plus ELSE 0 END) MUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.Men_20_plus ELSE 0 END) MUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.Men_20_plus ELSE 0 END) MUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.Men_20_plus ELSE 0 END) MUR5\n    FROM Unemployment_Rate u, MinMenUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate By Gender",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by gender over all relevant dates",
   "gridPos": { "h": 10, "w": 18, "x": 3, "y": 25 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT u.Date, u.Men_20_plus, u.Women_20_plus\nFROM Unemployment_Rate u"
    }
   ]
  },
  {
   "title": "COVID Cases By Gender ",
   "type": "barchart",
   "description": "Compare trends in COVID cases by gender over all relevant dates",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT g.MonthDate, g.Cases_Male, g.Cases_Female \nFROM COVID_Cases_By_Gender_Monthly g"
    }
   ]
  },
  {
   "title": "COVID Cases By Gender ",
   "type": "timeseries",
   "description": "Compare trends in COVID cases by gender over all relevant dates",
   "gridPos": { "h": 12, "w": 18, "x": 3, "y": 46 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT g.MonthDate, g.Cases_Male, g.Cases_Female \nFROM COVID_Cases_By_Gender_Monthly g"
    }
   ]
  }
 ]
}