{
 "title": "COVID and Unemployment Rate By Race",
 "description": "Presentation of COVID19 and its Effects on US Unemployment Rate",
 "time": { "from": "2019-12-01T05:00:00.000Z", "to": "2021-07-01T04:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "Gender", "query": "Men, Women" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">COVID-19 and Unemployment Rate By Race </h1>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For White",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for Whites at the peak periods of different COVID variants.",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.WUR1 AS Pre_COVID,\n       urate.WUR2 AS WildType_Peak, \n \t   urate.WUR3 AS Alpha_Peak, \n \t   urate.WUR4 AS Delta_Peak,\n \t   urate.WUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.White ELSE 0 END) WUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.White ELSE 0 END) WUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.White ELSE 0 END) WUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.White ELSE 0 END) WUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.White ELSE 0 END) WUR5\n    FROM Unemployment_Rate u, MinWhiteUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Whites",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by race to trends in COVID cases by race over all relevant dates",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 2 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT u.Date, u.White\nFROM Unemployment_Rate u;"
    },
    {
     "rawSql": "SELECT r.MonthDate, r.Cases_White\nFROM COVID_Cases_By_Race_Monthly r;\n"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Blacks",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by race to trends in COVID cases by race over all relevant dates",
   "gridPos": { "h": 11, "w": 14, "x": 0, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT u.Date, u.Black\nFROM Unemployment_Rate u;"
    },
    {
     "rawSql": "SELECT r.MonthDate, r.Cases_Black\nFROM COVID_Cases_By_Race_Monthly r;"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Black",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for Blacks at the peak periods of different COVID variants.",
   "gridPos": { "h": 11, "w": 10, "x": 14, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.BUR1 AS Pre_COVID,\n       urate.BUR2 AS WildType_Peak, \n \t   urate.BUR3 AS Alpha_Peak, \n \t   urate.BUR4 AS Delta_Peak,\n \t   urate.BUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.Black ELSE 0 END) BUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.Black ELSE 0 END) BUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.Black ELSE 0 END) BUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.Black ELSE 0 END) BUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.Black ELSE 0 END) BUR5\n    FROM Unemployment_Rate u, MinBlackUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;\n    "
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Hispanic",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for Hispanics at the peak periods of different COVID variants.",
   "gridPos": { "h": 11, "w": 9, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.HUR1 AS Pre_COVID,\n       urate.HUR2 AS WildType_Peak, \n \t   urate.HUR3 AS Alpha_Peak, \n \t   urate.HUR4 AS Delta_Peak,\n \t   urate.HUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.Hispanic ELSE 0 END) HUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.Hispanic ELSE 0 END) HUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.Hispanic ELSE 0 END) HUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.Hispanic ELSE 0 END) HUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.Hispanic ELSE 0 END) HUR5\n    FROM Unemployment_Rate u, MinHispanicUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Hispanics",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by race to trends in COVID cases by race over all relevant dates",
   "gridPos": { "h": 11, "w": 15, "x": 9, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT u.Date, u.Hispanic\nFROM Unemployment_Rate u;"
    },
    {
     "rawSql": "SELECT r.MonthDate, r.Cases_LatinX\nFROM COVID_Cases_By_Race_Monthly r;"
    }
   ]
  },
  {
   "title": "Unemployment Rate vs COVID Cases For Asians",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by race to trends in COVID cases by race over all relevant dates",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 35 },
   "targets": [
    {
     "rawSql": "SELECT u.Date, u.Asian\nFROM Unemployment_Rate u;"
    },
    {
     "rawSql": "SELECT r.MonthDate, r.Cases_Asian\nFROM COVID_Cases_By_Race_Monthly r;"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Asian",
   "type": "stat",
   "description": "Analyze the trend in unemployment rate for Asians at the peak periods of different COVID variants.",
   "gridPos": { "h": 10, "w": 10, "x": 14, "y": 35 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.AUR1 AS Pre_COVID,\n       urate.AUR2 AS WildType_Peak, \n \t   urate.AUR3 AS Alpha_Peak, \n \t   urate.AUR4 AS Delta_Peak,\n \t   urate.AUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.Asian ELSE 0 END) AUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.Asian ELSE 0 END) AUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.Asian ELSE 0 END) AUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.Asian ELSE 0 END) AUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.Asian ELSE 0 END) AUR5\n    FROM Unemployment_Rate u, MinAsianUnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate By Race",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by gender over all relevant dates",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 45 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT u.Date, u.White, u.Black, u.Hispanic, u.Asian\nFROM Unemployment_Rate u"
    }
   ]
  },
  {
   "title": "COVID Cases By Race",
   "type": "barchart",
   "description": "Compare trends in COVID cases by race over all relevant dates",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT r.MonthDate, r.Cases_White, r.Cases_Black, r.Cases_LatinX, r.Cases_Asian\nFROM COVID_Cases_By_Race_Monthly r\nWHERE r.MonthDate >= '2020-04-01'"
    }
   ]
  },
  {
   "title": "COVID Cases By Race",
   "type": "timeseries",
   "description": "Compare trends in COVID cases by race over all relevant dates",
   "gridPos": { "h": 11, "w": 18, "x": 3, "y": 67 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT r.MonthDate, r.Cases_White, r.Cases_Black, r.Cases_LatinX, r.Cases_Asian\nFROM COVID_Cases_By_Race_Monthly r"
    }
   ]
  }
 ]
}