{
 "title": "COVID & Industries and Sectors",
 "time": { "from": "2019-11-01", "to": "2022-08-01" },
 "templating": {
  "list": [
   { "name": "Sector", "query": "Private, Government" },
   {
    "name": "Private_Subgroup",
    "query": "Agriculture, Mining, Manufacturing, Retail Trade, Utilities, Financial Activities, Education/Health Services, Construction, Wholesale Trade, Transportation/Warehousing, Information, Professional/Business Services, Leisure/Hospitality, Other Services"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center;\"> COVID-19, Industries, and Economic Sectors </h1>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Quarterly GDP By Selected Private Sector Subgroups",
   "type": "timeseries",
   "description": "Compare trends in employment levels of the specific subdivisions of the private sector of the economy ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT m.MonthDate,\n\n(CASE WHEN '$Private_Subgroup' = 'Agriculture' THEN Agriculture END) AS Agriculture,\n\n(CASE WHEN '$Private_Subgroup' = 'Mining' THEN Mining END) AS Mining,\n\n(CASE WHEN '$Private_Subgroup' = 'Manufacturing' THEN Manufacturing END) AS Manufacturing,\n\n(CASE WHEN '$Private_Subgroup' = 'Retail Trade' THEN Retail_trade END) AS Retail_trade,\n\n(CASE WHEN '$Private_Subgroup' = 'Utilities' THEN Utilities END) AS Utilities,\n\n(CASE WHEN '$Private_Subgroup' = 'Financial Activities' THEN Financial_Activities END) AS Financial_Activities,\n\n(CASE WHEN '$Private_Subgroup' = 'Education/Health Services' THEN `Education_and_health services` END) AS Education_and_health_services,\n\n(CASE WHEN '$Private_Subgroup' = 'Construction' THEN Construction END) AS Construction,\n\n(CASE WHEN '$Private_Subgroup' = 'Wholesale Trade' THEN Wholesale_trade END) AS Wholesale_trade,\n\n(CASE WHEN '$Private_Subgroup' = 'Transportation/Warehousing' THEN Transportation_and_warehousing END) AS Transportation_and_warehousing,\n\n(CASE WHEN '$Private_Subgroup' = 'Information' THEN Information END) AS Information,\n\n(CASE WHEN '$Private_Subgroup' = 'Professional/Business Services' THEN Professional_and_business_services END) AS Professional_and_business_services,\n\n(CASE WHEN '$Private_Subgroup' = 'Leisure/Hospitality' THEN Leisure_and_Hospitality END) AS Leisure_and_Hospitality,\n\n(CASE WHEN '$Private_Subgroup' = 'Other Services' THEN Other_services END) AS Other_services\n\nFROM GDP_By_Industry g, MonthDate_To_Quarter m \nWHERE g.Quarter = m.Quarter;"
    }
   ]
  },
  {
   "title": "Peak Trends in GDP By Sector",
   "type": "stat",
   "description": "Analyze the trend in total unemployment rate at the peak periods of different COVID variants in comparison to the pre-COVID rate, defined as December 2019. ",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Pre_COVID, WildType_Peak, Alpha_Peak, Delta_Peak, Omicron_Peak\nFROM GDP_Peaks\nWHERE id = CASE '$Sector' \n    WHEN 'Private' THEN 'priv'\n    WHEN 'Government' THEN 'gov' END;"
    }
   ]
  },
  {
   "title": "National COVID Cases vs. Quarterly GDP By Overarching Economic Sector ",
   "type": "timeseries",
   "description": "Compare trends in GDP of the overarching private and government sectors of the economy to trends in COVID cases ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT m.MonthDate, \n\n(CASE WHEN '$Sector' = 'Private' THEN Total_Private END) AS Total_Private,\n\n(CASE WHEN '$Sector' = 'Government' THEN Government END) AS Government\n\nFROM GDP_By_Industry g, MonthDate_To_Quarter m \nWHERE g.Quarter = m.Quarter;\n"
    },
    {
     "rawSql": "SELECT c.MonthDate, c.Cases_Total\nFROM COVID_Cases_Monthly c"
    }
   ]
  },
  {
   "title": "Pre-COVID Age Group Breakdown of Employment Level",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 14, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ng.Agriculture, g.Mining, g.Manufacturing, g.Retail_trade, g.Utilities, g.Financial_Activities, g.`Education_and_health services`, g.Construction, g.Wholesale_trade, g.Transportation_and_warehousing, g.Information, g.Professional_and_business_services, g.Leisure_and_Hospitality, g.Other_services\n\nFROM GDP_By_Industry g, MaxPrivateGDP m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "title": "Wild Type Variant Peak Age Group Breakdown of Employment Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 2, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ng.Agriculture, g.Mining, g.Manufacturing, g.Retail_trade, g.Utilities, g.Financial_Activities, g.`Education_and_health services`, g.Construction, g.Wholesale_trade, g.Transportation_and_warehousing, g.Information, g.Professional_and_business_services, g.Leisure_and_Hospitality, g.Other_services\n\nFROM GDP_By_Industry g, MaxCaseWT m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "title": "Wild Type Variant Peak Age Group Breakdown of Employment Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 2, "y": 49 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ng.Agriculture, g.Mining, g.Manufacturing, g.Retail_trade, g.Utilities, g.Financial_Activities, g.`Education_and_health services`, g.Construction, g.Wholesale_trade, g.Transportation_and_warehousing, g.Information, g.Professional_and_business_services, g.Leisure_and_Hospitality, g.Other_services\n\nFROM GDP_By_Industry g, MaxCaseAlpha m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  }
 ]
}