{
 "title": "COVID and Government Sector GDP",
 "time": { "from": "2019-11-01", "to": "2022-08-01" },
 "templating": {
  "list": [
   { "name": "Government_Subgroup", "query": "Federal, State and Local" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center;\"> COVID-19 and Government Sector GDP </h1>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Peak Trends in Government Sector GDP ",
   "type": "stat",
   "description": "Analyze the government sector GDP during peak periods of different COVID variants in comparison to the pre-COVID rate",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Pre_COVID, WildType_Peak, Alpha_Peak, Delta_Peak, Omicron_Peak\nFROM GDP_Peaks\nWHERE id = 'gov';"
    }
   ]
  },
  {
   "title": "National COVID Cases vs. Government Sector Quarterly GDP",
   "type": "timeseries",
   "description": "Compare trends in GDP of the overarching government sector of the economy to trends in COVID cases",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT m.MonthDate, Government \nFROM GDP_By_Industry g, MonthDate_To_Quarter m \nWHERE g.Quarter = m.Quarter;\n"
    },
    {
     "rawSql": "SELECT c.MonthDate, c.Cases_Total\nFROM COVID_Cases_Monthly c"
    }
   ]
  },
  {
   "title": "Quarterly GDP By Selected Government Sector Subgroups",
   "type": "timeseries",
   "description": "Compare trends in GDP of the specific subdivisions of the government sector of the economy ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT m.MonthDate,\n\n(CASE WHEN '$Government_Subgroup' = 'Federal' THEN Federal END) AS Federal,\n\n(CASE WHEN '$Government_Subgroup' = 'State and Local' THEN State_and_local END) AS State_and_local\n\nFROM GDP_By_Industry g, MonthDate_To_Quarter m \nWHERE g.Quarter = m.Quarter;"
    }
   ]
  },
  {
   "title": "Wild Type Variant Peak Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT g.Federal, g.State_and_local\nFROM GDP_By_Industry g, MaxCaseWT m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 4, "w": 12, "x": 6, "y": 32 },
   "options": {
    "content": "<h1>                                                                                    \r\n    \r\n    \r\n     </h1>\r\n\r\n     <h1>                                                                                    \r\n    \r\n    \r\n     </h1>\r\n    \r\n<h1 style=\"text-align: center;\"> \r\n    \r\n    \r\n    Subgroup Breakdown of\r\n    \r\n    \r\n     </h1>\r\n\r\n    <h1 style=\"text-align: center;\">  Government Sector GDP\r\n\r\n</h1>\r\n\r\n\r\n\r\n    \r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Delta Type Variant Peak Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT g.Federal, g.State_and_local\nFROM GDP_By_Industry g, MaxCaseDelta m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "title": "Pre-COVID Breakdown",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 6, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT g.Federal, g.State_and_local\nFROM GDP_By_Industry g, MaxGovGDP m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "title": "Alpha Type Variant Peak Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT g.Federal, g.State_and_local\nFROM GDP_By_Industry g, MaxCaseAlpha m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "title": "Omicron Variant Peak Breakdown",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 6, "x": 18, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT g.Federal, g.State_and_local\nFROM GDP_By_Industry g, MaxCaseOmicron m \nWHERE g.Quarter = m.Quarter;\n\n"
    }
   ]
  }
 ]
}