{
 "title": "COVID and National Economic Factors",
 "description": "Presentation of COVID19 and its Effects on US Economic Factors",
 "time": { "from": "2019-10-01", "to": "2022-09-30" },
 "templating": {
  "list": [
   {
    "name": "Economic_Factor",
    "label": "Economic Factor",
    "query": "Unemployment Rate, Personal Saving Rate, Gross Domestic Product,  Personal Income, Personal Saving"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center;\"> COVID-19 and National Economic Factors </h1>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Number of COVID Cases At Peak Point of Different Variants",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT wt.mx Max_Cases_WildType, a.mx Max_Cases_Alpha, d.mx Max_Cases_Delta, o.mx Max_Cases_Omicron\r\nFROM MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron as o"
    }
   ]
  },
  {
   "title": "Peak Trends in National Economic Factors",
   "type": "stat",
   "description": "Analyze the trend in total unemployment rate at the peak periods of different COVID variants in comparison to the pre-COVID rate, defined as December 2019. ",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Pre_COVID, WildType_Peak, Alpha_Peak, Delta_Peak, Omicron_Peak\nFROM Natl_Econ_Peaks\nWHERE id = CASE '$Economic_Factor' WHEN 'Unemployment Rate' THEN 'ur'\n                                   WHEN 'Gross Domestic Product' THEN 'gdp'\n                                   WHEN 'Personal Income' THEN 'pi'\n                                   WHEN 'Personal Saving Rate' THEN 'ps'\n            END;"
    }
   ]
  },
  {
   "title": "National COVID Cases vs. National Levels of Different Economic Factors",
   "type": "timeseries",
   "description": "Compare trends in economic factors to trends in COVID cases over all relevant dates. ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT \nDate, \n(CASE WHEN '$Economic_Factor' = 'Unemployment Rate' THEN Unemployment_Rate END) AS Unemployment_Rate,\n\n(CASE WHEN '$Economic_Factor' = 'Gross Domestic Product' THEN GDP END) AS Gross_Domestic_Product,\n\n(CASE WHEN '$Economic_Factor' = 'Personal Income' THEN Personal_Income END) AS Personal_Income, \n\n(CASE WHEN '$Economic_Factor' = 'Personal Saving Rate' THEN Personal_Saving_Rate\nEND) AS Personal_Saving_Rate\n\nFROM Total_Economic_Factors\n"
    },
    {
     "rawSql": "SELECT c.MonthDate, c.Cases_Total\nFROM COVID_Cases_Monthly c"
    }
   ]
  }
 ]
}