{
 "title": "COVID and Unemployment Rate By Age",
 "description": "Presentation of COVID19 and its Effects on US Unemployment Rate",
 "time": { "from": "2019-12-31", "to": "2022-09-30" },
 "templating": {
  "list": [
   { "name": "Gender", "query": "Men, Women" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center;\">COVID-19 and Unemployment Rate By Age </h1>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Ages 16 to 19",
   "type": "stat",
   "description": "Compare unemployment rates of working 16 to 19-year-olds to those 20 years and over at the peak periods of different COVID variants in comparison to the pre-COVID rate, defined as December 2019. Has COVID disproportionately affected certain age groups in terms of employment?",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.LUR1 AS Pre_COVID,\n       urate.LUR2 AS WildType_Peak, \n \t   urate.LUR3 AS Alpha_Peak, \n \t   urate.LUR4 AS Delta_Peak,\n \t   urate.LUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN u.Yrs_16_19 ELSE 0 END) LUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN u.Yrs_16_19 ELSE 0 END) LUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN u.Yrs_16_19 ELSE 0 END) LUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN u.Yrs_16_19 ELSE 0 END) LUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN u.Yrs_16_19 ELSE 0 END) LUR5\n    FROM Unemployment_Rate u, MinL20UnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Trends in Unemployment Rate For Ages 20 and Over",
   "type": "stat",
   "description": "Compare unemployment rates of working 16 to 19-year-olds to those 20 years and over at the peak periods of different COVID variants in comparison to the pre-COVID rate, defined as December 2019. Has COVID disproportionately affected certain age groups in terms of employment?",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT urate.GUR1 AS Pre_COVID,\n       urate.GUR2 AS WildType_Peak, \n \t   urate.GUR3 AS Alpha_Peak, \n \t   urate.GUR4 AS Delta_Peak,\n \t   urate.GUR5 AS Omicron_Peak\nFROM\n    (SELECT SUM(CASE WHEN u.Date=m.Date THEN ((u.Men_20_plus + u.Women_20_plus) / 2) ELSE 0 END) GUR1,\n           SUM(CASE WHEN u.Date=wt.MonthDate THEN ((u.Men_20_plus + u.Women_20_plus) / 2) ELSE 0 END) GUR2,\n           SUM(CASE WHEN u.Date=a.MonthDate THEN ((u.Men_20_plus + u.Women_20_plus) / 2) ELSE 0 END) GUR3,\n           SUM(CASE WHEN u.Date=d.MonthDate THEN ((u.Men_20_plus + u.Women_20_plus) / 2) ELSE 0 END) GUR4,\n           SUM(CASE WHEN u.Date=o.MonthDate THEN ((u.Men_20_plus + u.Women_20_plus) / 2) ELSE 0 END) GUR5\n    FROM Unemployment_Rate u, MinG20UnempRate as m, MaxCaseWT as wt, MaxCaseAlpha as a, MaxCaseDelta as d, MaxCaseOmicron o\n    WHERE u.Date in (m.Date, wt.MonthDate, a.MonthDate, d.MonthDate, o.MonthDate)) urate;"
    }
   ]
  },
  {
   "title": "Unemployment Rate By Age vs COVID Cases For All Ages",
   "type": "timeseries",
   "description": "Compare trends in unemployment rate by gender to trends in COVID cases by gender over all relevant dates",
   "gridPos": { "h": 12, "w": 20, "x": 2, "y": 10 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT u.Date, c.MonthDate, u.Yrs_16_19, ((u.Men_20_plus + u.Women_20_plus) / 2) as Yrs_20up, c.Cases_Total\nFROM Unemployment_Rate u, COVID_Cases_Monthly c\nWHERE u.Date = c.MonthDate;"
    }
   ]
  },
  {
   "title": "Employment Level By Age Group",
   "type": "timeseries",
   "description": "Compare employment levels for all age groups over all relevant dates",
   "gridPos": { "h": 12, "w": 20, "x": 2, "y": 22 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT e.Date, e.Yrs_16_19, e.Yrs_20_24, e.Yrs_25_34, e.Yrs_35_44, e.Yrs_45_54, e.Yrs_55_up\nFROM EmpLevelAgeCol e;"
    }
   ]
  },
  {
   "title": "Wild Type Variant Peak Age Group Breakdown of Employment Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT e.Yrs_16_19, e.Yrs_20_24, e.Yrs_25_34, e.Yrs_35_44, e.Yrs_45_54, e.Yrs_55_up\nFROM EmpLevelAgeCol e, MaxCaseWT m\nWHERE e.Date = m.MonthDate;\n"
    }
   ]
  },
  {
   "title": "Pre-COVID Age Group Breakdown of Employment Level",
   "type": "piechart",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 34 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT e.Yrs_16_19, e.Yrs_20_24, e.Yrs_25_34, e.Yrs_35_44, e.Yrs_45_54, e.Yrs_55_up\nFROM EmpLevelAgeCol e, MaxEmpLevel m\nWHERE e.Date = m.Date;\n"
    }
   ]
  },
  {
   "title": " Alpha Variant Peak Age Group Breakdown of Employment Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT e.Yrs_16_19, e.Yrs_20_24, e.Yrs_25_34, e.Yrs_35_44, e.Yrs_45_54, e.Yrs_55_up\nFROM EmpLevelAgeCol e, MaxCaseAlpha m\nWHERE e.Date = m.MonthDate;\n"
    }
   ]
  },
  {
   "title": "Delta Variant Peak Age Group Breakdown of Employment Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT e.Yrs_16_19, e.Yrs_20_24, e.Yrs_25_34, e.Yrs_35_44, e.Yrs_45_54, e.Yrs_55_up\nFROM EmpLevelAgeCol e, MaxCaseDelta m\nWHERE e.Date = m.MonthDate;\n"
    }
   ]
  },
  {
   "title": "Omicron Variant Peak Age Group Breakdown of Employment Level",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT e.Yrs_16_19, e.Yrs_20_24, e.Yrs_25_34, e.Yrs_35_44, e.Yrs_45_54, e.Yrs_55_up\nFROM EmpLevelAgeCol e, MaxCaseOmicron m\nWHERE e.Date = m.MonthDate;\n"
    }
   ]
  }
 ]
}