{
 "title": "COVID and Private Sector GDP",
 "time": { "from": "2019-11-01", "to": "2022-08-01" },
 "templating": {
  "list": [
   {
    "name": "Private_Subgroup",
    "query": "Agriculture, Mining, Manufacturing, Retail Trade, Utilities, Financial Activities, Education/Health Services, Construction, Wholesale Trade, Transportation/Warehousing, Information, Professional/Business Services, Leisure/Hospitality, Other Services"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "<h1 style=\"text-align: center;\"> COVID-19 and Private Sector GDP </h1>\r\n"
   },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT Date,Cases_Asian,Cases_White,Cases_Black,Cases_Latinx FROM jhu_315_final_project.COVID_Cases_By_Race ORDER BY Cases_Total DESC\r\n) as b LIMIT 1"
    }
   ]
  },
  {
   "title": "Peak Trends in Private Sector GDP",
   "type": "stat",
   "description": "Analyze the private sector GDP during peak periods of different COVID variants in comparison to the pre-COVID rate ",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Pre_COVID, WildType_Peak, Alpha_Peak, Delta_Peak, Omicron_Peak\nFROM GDP_Peaks\nWHERE id = 'priv';"
    }
   ]
  },
  {
   "title": "National COVID Cases vs. Private Sector Quarterly GDP",
   "type": "timeseries",
   "description": "Compare trends in GDP of the overarching private sector of the economy to trends in COVID cases ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 6 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT m.MonthDate, Total_Private \nFROM GDP_By_Industry g, MonthDate_To_Quarter m \nWHERE g.Quarter = m.Quarter;\n\n"
    },
    {
     "rawSql": "SELECT c.MonthDate, c.Cases_Total\nFROM COVID_Cases_Monthly c"
    }
   ]
  },
  {
   "title": "Quarterly GDP By Selected Private Sector Industry Subgroups",
   "type": "timeseries",
   "description": "Compare trends in GDP of the specific subdivisions of the private sector of the economy ",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 19 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT m.MonthDate,\n\n(CASE WHEN '$Private_Subgroup' = 'Agriculture' THEN Agriculture END) AS Agriculture,\n\n(CASE WHEN '$Private_Subgroup' = 'Mining' THEN Mining END) AS Mining,\n\n(CASE WHEN '$Private_Subgroup' = 'Manufacturing' THEN Manufacturing END) AS Manufacturing,\n\n(CASE WHEN '$Private_Subgroup' = 'Retail Trade' THEN Retail_trade END) AS Retail_trade,\n\n(CASE WHEN '$Private_Subgroup' = 'Utilities' THEN Utilities END) AS Utilities,\n\n(CASE WHEN '$Private_Subgroup' = 'Financial Activities' THEN Financial_Activities END) AS Financial_Activities,\n\n(CASE WHEN '$Private_Subgroup' = 'Education/Health Services' THEN `Education_and_health services` END) AS Education_and_health_services,\n\n(CASE WHEN '$Private_Subgroup' = 'Construction' THEN Construction END) AS Construction,\n\n(CASE WHEN '$Private_Subgroup' = 'Wholesale Trade' THEN Wholesale_trade END) AS Wholesale_trade,\n\n(CASE WHEN '$Private_Subgroup' = 'Transportation/Warehousing' THEN Transportation_and_warehousing END) AS Transportation_and_warehousing,\n\n(CASE WHEN '$Private_Subgroup' = 'Information' THEN Information END) AS Information,\n\n(CASE WHEN '$Private_Subgroup' = 'Professional/Business Services' THEN Professional_and_business_services END) AS Professional_and_business_services,\n\n(CASE WHEN '$Private_Subgroup' = 'Leisure/Hospitality' THEN Leisure_and_Hospitality END) AS Leisure_and_Hospitality,\n\n(CASE WHEN '$Private_Subgroup' = 'Other Services' THEN Other_services END) AS Other_services\n\nFROM GDP_By_Industry g, MonthDate_To_Quarter m \nWHERE g.Quarter = m.Quarter;"
    }
   ]
  },
  {
   "title": "Wild Type Variant Peak",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ng.Agriculture, g.Mining, g.Manufacturing, g.Retail_trade, g.Utilities, g.Financial_Activities, g.`Education_and_health services`, g.Construction, g.Wholesale_trade, g.Transportation_and_warehousing, g.Information, g.Professional_and_business_services, g.Leisure_and_Hospitality, g.Other_services\n\nFROM GDP_By_Industry g, MaxCaseWT m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "title": "Pre-COVID Private Sector Subgroup Breakdown of GDP",
   "type": "piechart",
   "gridPos": { "h": 18, "w": 9, "x": 7, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ng.Agriculture, g.Mining, g.Manufacturing, g.Retail_trade, g.Utilities, g.Financial_Activities, g.`Education_and_health services`, g.Construction, g.Wholesale_trade, g.Transportation_and_warehousing, g.Information, g.Professional_and_business_services, g.Leisure_and_Hospitality, g.Other_services\n\nFROM GDP_By_Industry g, MaxPrivateGDP m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "title": "Delta Type Variant Peak",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ng.Agriculture, g.Mining, g.Manufacturing, g.Retail_trade, g.Utilities, g.Financial_Activities, g.`Education_and_health services`, g.Construction, g.Wholesale_trade, g.Transportation_and_warehousing, g.Information, g.Professional_and_business_services, g.Leisure_and_Hospitality, g.Other_services\n\nFROM GDP_By_Industry g, MaxCaseDelta m \nWHERE g.Quarter = m.Quarter;"
    }
   ]
  },
  {
   "title": "Alpha Variant Peak ",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ng.Agriculture, g.Mining, g.Manufacturing, g.Retail_trade, g.Utilities, g.Financial_Activities, g.`Education_and_health services`, g.Construction, g.Wholesale_trade, g.Transportation_and_warehousing, g.Information, g.Professional_and_business_services, g.Leisure_and_Hospitality, g.Other_services\n\nFROM GDP_By_Industry g, MaxCaseAlpha m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  },
  {
   "title": "Omicron Variant Peak",
   "type": "piechart",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 41 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\ng.Agriculture, g.Mining, g.Manufacturing, g.Retail_trade, g.Utilities, g.Financial_Activities, g.`Education_and_health services`, g.Construction, g.Wholesale_trade, g.Transportation_and_warehousing, g.Information, g.Professional_and_business_services, g.Leisure_and_Hospitality, g.Other_services\n\nFROM GDP_By_Industry g, MaxCaseOmicron m \nWHERE g.Quarter = m.Quarter;\n"
    }
   ]
  }
 ]
}