{
 "title": "National COVID Trends by Gender and Age",
 "tags": [
  "JHU-315",
  "Health"
 ],
 "time": { "from": "2020-12-13T00:00:00.000Z", "to": "2022-11-16T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "Sex", "query": "Female, Male, All Sex\n" },
   {
    "name": "Variant",
    "query": "Wild Type, Alpha, Delta, Omicron "
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<h1 style=\"text-align: center;\">National COVID Health Outcomes for Gender and Age</h1>\n\n<div style=\"text-align: center;\">Note: Due to a grafana bug, to view the data toggle the \"Sex\" button</div>\n"
   }
  },
  {
   "title": "Deaths and Vaccinations Over time - National",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 16, "x": 0, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT Date, SUM(Total_Deaths) AS Total_Deaths FROM COVID_Deaths_By_Age_Gender \r\nWHERE Sex = '$Sex' GROUP BY Date"
    },
    {
     "rawSql": "SELECT Date, SUM(Admin_Dose_1_Daily) AS Administered_Daily FROM COVID_Vaccinations GROUP BY Date"
    }
   ]
  },
  {
   "title": "Cases By Sex",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 3 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Sex' = 'Male' THEN SUM(Male_Count)\r\n      WHEN '$Sex' = 'Female' THEN SUM(Female_Count)\r\n      WHEN '$Sex' = 'All Sex' THEN SUM(Total_Count)\r\n    END\r\n  ) AS Total_Cases\r\nFROM\r\n  COVID_Cases_By_Gender\r\nGROUP BY\r\n  Date"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 16, "x": 0, "y": 10 },
   "options": {
    "content": "Note, Administered_Daily is for all sexes for above graph."
   }
  },
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 12 },
   "options": {
    "content": "\n<h1 style=\"text-align: center;\"> $Variant\n</h1>\n<div style=\"text-align: center;\"> Variant Selection\n</div>\n\n\n\n"
   },
   "targets": [
    {
     "sql": {
      "columns": [
       {
        "parameters": [],
        "type": "function"
       }
      ],
      "groupBy": [
       { "property": { "type": "string" }, "type": "groupBy" }
      ],
      "limit": 50
     }
    }
   ]
  },
  {
   "title": "Deaths Breakdown for Males Per Variant",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nAge_Group,\r\n(CASE \r\nWHEN  '$Variant' = 'Wild Type' THEN (Total_Deaths_M_WT) \r\nWHEN  '$Variant' = 'Alpha' THEN (Total_Deaths_M_Alpha) \r\nWHEN  '$Variant' = 'Delta' THEN (Total_Deaths_M_Delta) \r\nWHEN  '$Variant' = 'Omicron' THEN (Total_Deaths_M_Omicron)\r\nEND) as Total_Cases\r\nFROM COVID_Deaths_Age_M_Breakdown  "
    }
   ]
  },
  {
   "title": "Deaths Breakdown for Females Per Variant",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nAge_Group,\r\n(CASE \r\nWHEN  '$Variant' = 'Wild Type' THEN (Total_Deaths_F_WT) \r\nWHEN  '$Variant' = 'Alpha' THEN (Total_Deaths_F_Alpha) \r\nWHEN  '$Variant' = 'Delta' THEN (Total_Deaths_F_Delta) \r\nWHEN  '$Variant' = 'Omicron' THEN (Total_Deaths_F_Omicron)\r\nEND) as Total_Cases\r\nFROM COVID_Deaths_Age_F_Breakdown  "
    }
   ]
  },
  {
   "title": "Deaths Breakdown for Totals Per Variant",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nAge_Group,\r\n(CASE \r\nWHEN  '$Variant' = 'Wild Type' THEN (Total_Deaths_T_WT) \r\nWHEN  '$Variant' = 'Alpha' THEN (Total_Deaths_T_Alpha) \r\nWHEN  '$Variant' = 'Delta' THEN (Total_Deaths_T_Delta) \r\nWHEN  '$Variant' = 'Omicron' THEN (Total_Deaths_T_Omicron)\r\nEND) as Total_Cases\r\nFROM COVID_Deaths_Age_T_Breakdown  "
    }
   ]
  },
  {
   "title": "COVID Cases By Gender as a Percentage of Total Population",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "rawSql": "SELECT \r\n State,\r\n(CASE \r\nWHEN '$Sex' = 'Male' AND '$Variant' = 'Wild Type' THEN SUM(Male_Count_WT) \r\nWHEN '$Sex' = 'Male' AND '$Variant' = 'Alpha' THEN SUM(Male_Count_Alpha) \r\nWHEN '$Sex' = 'Male' AND '$Variant' = 'Delta' THEN SUM(Male_Count_Delta) \r\nWHEN '$Sex' = 'Male' AND '$Variant' = 'Omicron' THEN SUM(Male_Count_Omicron) \r\nWHEN '$Sex' = 'Female' AND '$Variant' = 'Wild Type' THEN SUM(Female_Count_WT) \r\nWHEN '$Sex' = 'Female' AND '$Variant' = 'Alpha' THEN SUM(Female_Count_Alpha) \r\nWHEN '$Sex' = 'Female' AND '$Variant' = 'Delta' THEN SUM(Female_Count_Delta) \r\nWHEN '$Sex' = 'Female' AND '$Variant' = 'Omicron' THEN SUM(Female_Count_Omicron) \r\nWHEN '$Sex' = 'All Sex' AND '$Variant' = 'Wild Type' THEN SUM(Total_Count_WT) \r\nWHEN '$Sex' = 'All Sex' AND '$Variant' = 'Alpha' THEN SUM(Total_Count_Alpha) \r\nWHEN '$Sex' = 'All Sex' AND '$Variant' = 'Delta' THEN SUM(Total_Count_Delta) \r\nWHEN '$Sex' = 'All Sex' AND '$Variant' = 'Omicron' THEN SUM(Total_Count_Omicron) \r\nEND)/Total as Total_Cases\r\nFROM COVID_Cases_By_Gender_AllVariants NATURAL JOIN US_Population_Racial GROUP BY State"
    }
   ]
  },
  {
   "title": "COVID Vaccinations Doses Per Population",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 23 },
   "targets": [
    {
     "rawSql": "SELECT \r\nState,JabPerPop\r\nFROM Jabs_Per_Population_State"
    }
   ]
  }
 ]
}