{
 "title": "National COVID And Patient Outcomes By Race",
 "description": "Presentation of COVID19 and its Effects on Outcomes",
 "time": { "from": "2021-02-06T16:41:41.217Z", "to": "2021-02-11T06:06:47.061Z" },
 "templating": {
  "list": [
   { "name": "Racial_Group", "query": "SELECT * FROM Racial_Category" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<h1 style=\"text-align: center;\">National Trends By Race</h1>\n\n"
   }
  },
  {
   "title": "Wild Type Variant Peak Statistics ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 0, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND)) as Deaths\r\n\r\nFROM MaxDeathsWT"
    },
    {
     "rawSql": "SELECT \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND)) as Cases\r\n\r\nFROM MaxCasesWT"
    },
    {
     "rawSql": "SELECT \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND)) as Hospitalizations\r\n\r\nFROM MaxHospWT"
    }
   ]
  },
  {
   "title": "Alpha Type Variant Peak Statistics ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 6, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND)) as Deaths\r\n\r\nFROM MaxDeathsAlpha"
    },
    {
     "rawSql": "SELECT \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND)) as Cases\r\n\r\nFROM MaxCasesAlpha"
    },
    {
     "rawSql": "SELECT \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND)) as Hospitalizations\r\n\r\nFROM MaxHospAlpha"
    }
   ]
  },
  {
   "title": "General Delta Type Variant Peak Statistics ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 12, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM MaxDeathsDeltaGeneral\r\n"
    },
    {
     "rawSql": "SELECT mx as Cases FROM MaxCaseDelta"
    },
    {
     "rawSql": "SELECT \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND)) as Hospitalizations\r\n\r\nFROM MaxHospDelta"
    }
   ]
  },
  {
   "title": "General Omicron Type Variant Peak Statistics ",
   "type": "stat",
   "gridPos": { "h": 3, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM MaxDeathsDeltaGeneral"
    },
    {
     "rawSql": "SELECT mx as Cases FROM MaxCaseOmicron"
    },
    {
     "rawSql": "SELECT \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND)) as Hospitalizations\r\n\r\nFROM MaxHospDelta"
    }
   ]
  },
  {
   "title": "Statistics for WildType",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT Date,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND) as Total_Deaths\r\n\r\nFROM DeathsWT"
    },
    {
     "rawSql": "SELECT Date,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND) as Total_Cases\r\n\r\nFROM CasesWT"
    },
    {
     "rawSql": "SELECT Date,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Total_Hosp\r\n\r\nFROM HospWT"
    }
   ]
  },
  {
   "title": "Statistics for WildType",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT Date,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND) as Total_Deaths\r\n\r\nFROM DeathsAlpha"
    },
    {
     "rawSql": "SELECT Date,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND) as Total_Cases\r\n\r\nFROM CasesAlpha"
    },
    {
     "rawSql": "SELECT Date,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Total_Hosp\r\n\r\nFROM HospAlpha"
    }
   ]
  },
  {
   "title": "Cases, Tests, and Deaths Per Race Nationally",
   "type": "timeseries",
   "description": "National Trends of Cases, Deaths, and Tests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
   "targets": [
    {
     "rawSql": "SELECT \r\nDate, \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND)) as Total_Cases\r\nFROM COVID_Cases_By_Race GROUP BY Date"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Tests_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Tests_Black\r\nWHEN '$Racial_Group' = 'White' THEN Tests_White\r\nWHEN '$Racial_Group' = 'Total' THEN Tests_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Tests_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Tests_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Tests_NHPI\r\nEND)) as Total_Tests\r\nFROM COVID_Test_By_Race GROUP BY Date"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND)) as Total_Deaths\r\nFROM COVID_Deaths_By_Race GROUP BY Date"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND)) as Total_Hospitalizations\r\nFROM COVID_Hospitalizations_By_Race GROUP BY Date"
    }
   ]
  },
  {
   "title": "State Population By Selected Racial Group",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\r\n\r\nSELECT \r\nState, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN AsianTotal\r\nWHEN '$Racial_Group' = 'Black' THEN BlackTotal\r\nWHEN '$Racial_Group' = 'White' THEN WhiteTotal\r\nWHEN '$Racial_Group' = 'Latinx' THEN OtherTotal\r\nWHEN '$Racial_Group' = 'AIAN' THEN HawaiianTotal\r\nWHEN '$Racial_Group' = 'NHPI' THEN IndianTotal\r\nEND) as Population_Percentage\r\nFROM US_Population_Racial"
    }
   ]
  },
  {
   "title": "Cumulative  Hospitalizations By State Per Race",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT State_To_Code.State_Name, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN SUM(Hosp_Asian)\r\nWHEN '$Racial_Group' = 'Black' THEN SUM(Hosp_Black)\r\nWHEN '$Racial_Group' = 'White' THEN SUM(Hosp_White)\r\nWHEN '$Racial_Group' = 'Total' THEN SUM(Hosp_Total)\r\nWHEN '$Racial_Group' = 'Latinx' THEN SUM(Hosp_Latinx)\r\nWHEN '$Racial_Group' = 'AIAN' THEN SUM(Hosp_AIAN)\r\nWHEN '$Racial_Group' = 'NHPI' THEN SUM(Hosp_NHPI)\r\nEND) AS Total_Cases\r\nFROM COVID_Hospitalizations_By_Race JOIN State_To_Code ON\r\nCOVID_Hospitalizations_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name;"
    }
   ]
  },
  {
   "title": "Cumulative Tests By State Per Race",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 6, "x": 18, "y": 13 },
   "targets": [
    {
     "rawSql": "SELECT State_To_Code.State_Name, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN SUM(Tests_Asian)\r\nWHEN '$Racial_Group' = 'Black' THEN SUM(Tests_Black)\r\nWHEN '$Racial_Group' = 'White' THEN SUM(Tests_White)\r\nWHEN '$Racial_Group' = 'Total' THEN SUM(Tests_Total)\r\nWHEN '$Racial_Group' = 'Latinx' THEN SUM(Tests_Latinx)\r\nWHEN '$Racial_Group' = 'AIAN' THEN SUM(Tests_AIAN)\r\nWHEN '$Racial_Group' = 'NHPI' THEN SUM(Tests_NHPI)\r\nEND) AS Total_Tests\r\nFROM COVID_Test_By_Race JOIN State_To_Code ON\r\nCOVID_Test_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name;"
    }
   ]
  },
  {
   "title": "Cumulative Cases By State Per Race",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT State_To_Code.State_Name, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN SUM(Cases_Asian)\r\nWHEN '$Racial_Group' = 'Black' THEN SUM(Cases_Black)\r\nWHEN '$Racial_Group' = 'White' THEN SUM(Cases_White)\r\nWHEN '$Racial_Group' = 'Total' THEN SUM(Cases_Total)\r\nWHEN '$Racial_Group' = 'Latinx' THEN SUM(Cases_Latinx)\r\nWHEN '$Racial_Group' = 'AIAN' THEN SUM(Cases_AIAN)\r\nWHEN '$Racial_Group' = 'NHPI' THEN SUM(Cases_NHPI)\r\nEND) AS Total_Cases\r\nFROM COVID_Cases_By_Race JOIN State_To_Code ON\r\nCOVID_Cases_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name;"
    }
   ]
  },
  {
   "title": "Cumulative  Deaths By State Per Race",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 24 },
   "targets": [
    {
     "rawSql": "SELECT State_To_Code.State_Name, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN SUM(Deaths_Asian)\r\nWHEN '$Racial_Group' = 'Black' THEN SUM(Deaths_Black)\r\nWHEN '$Racial_Group' = 'White' THEN SUM(Deaths_White)\r\nWHEN '$Racial_Group' = 'Total' THEN SUM(Deaths_Total)\r\nWHEN '$Racial_Group' = 'Latinx' THEN SUM(Deaths_Latinx)\r\nWHEN '$Racial_Group' = 'AIAN' THEN SUM(Deaths_AIAN)\r\nWHEN '$Racial_Group' = 'NHPI' THEN SUM(Deaths_NHPI)\r\nEND) AS Total_Cases\r\nFROM COVID_Deaths_By_Race JOIN State_To_Code ON\r\nCOVID_Deaths_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name;"
    }
   ]
  }
 ]
}