{
 "title": "National COVID-Analysis-Insurance-Coverage",
 "tags": [
  "Parent",
  "Insurance"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Insurance_Type",
    "query": "Employer,Non-Group,Medicaid,Medicare,Military,Uninsured,"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<h1 style=\"text-align: center;\">National Breakdown of Insured Populations</h1>\n\n<div style=\"text-align: center;\">2021 Data</div>\n"
   }
  },
  {
   "type": "geomap",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT\r\n  State_Name,\r\n  latitude,\r\n  longitude,\r\n  (CASE\r\n      WHEN '$Insurance_Type' = 'Employer' THEN Employer\r\n      WHEN '$Insurance_Type' = 'Non-Group' THEN NonGroup\r\n      WHEN '$Insurance_Type' = 'Military' THEN Military\r\n      WHEN '$Insurance_Type' = 'Medicare' THEN Medicare\r\n      WHEN '$Insurance_Type' = 'Medicaid' THEN Medicaid\r\n      WHEN '$Insurance_Type' = 'Uninsured' THEN Uninsured\r\n      END\r\n) as Percent_Insured_By_Policy\r\nFROM\r\n  State_Loc_MeshedWithInsurance\r\n\r\n  "
    },
    {
     "rawSql": "SELECT\r\n  State_Name,\r\n  (CASE\r\n      WHEN '$Insurance_Type' = 'Employer' THEN Employer\r\n      WHEN '$Insurance_Type' = 'Non-Group' THEN NonGroup\r\n      WHEN '$Insurance_Type' = 'Military' THEN Military\r\n      WHEN '$Insurance_Type' = 'Medicare' THEN Medicare\r\n      WHEN '$Insurance_Type' = 'Medicaid' THEN Medicaid\r\n      WHEN '$Insurance_Type' = 'Uninsured' THEN Uninsured\r\n      END\r\n) as Percent_Insured_By_Policy\r\nFROM\r\n  State_Loc_MeshedWithInsurance\r\n\r\n  "
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 13 },
   "options": {
    "content": "\n<h1 style=\"text-align: center;\">Additional COVID Metrics By State</h1>\n\n"
   }
  },
  {
   "title": "COVID Cases By State",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT State_Name, SUM(new_cases) as Cases FROM COVID_Cases_By_State_With_Name GROUP BY State_Name"
    }
   ]
  },
  {
   "title": "COVID Deaths By State",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 8, "x": 8, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT State_To_Code.State_Name,Deaths_Total\r\nFROM COVID_Deaths_By_Race JOIN State_To_Code ON\r\nCOVID_Deaths_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name;"
    }
   ]
  },
  {
   "title": "COVID Hospitalizations By State",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT State_To_Code.State_Name, Hosp_Total\r\nFROM COVID_Hospitalizations_By_Race JOIN State_To_Code ON\r\nCOVID_Hospitalizations_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name;"
    }
   ]
  }
 ]
}