{
 "title": "National COVID Statistics And Patient Outcomes By Race",
 "description": "Presentation of COVID19 and its Effects on Outcomes",
 "tags": [
  "Race",
  "National"
 ],
 "time": { "from": "2021-02-06T16:41:41.217Z", "to": "2021-02-11T06:06:47.061Z" },
 "templating": {
  "list": [
   {
    "name": "Racial_Group",
    "query": "Total,White,Black,Latinx,Asian,AIAN,NHPI"
   },
   { "name": "Variant", "query": "Wild Type, Alpha\n" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<h1 style=\"text-align: center;\">National COVID Statistics And Patient Outcomes By Race and Political Affiliation </h1>\n<div style=\"text-align: center;\">For more information for a particular state, please visit the parent page and select state dashboards.</div>\n\n"
   }
  },
  {
   "title": "$Variant Variant Peak Statistics ",
   "type": "stat",
   "description": "Peak statistics, the most of any quantity on a day for a given race and variant. ",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\n      WHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\n      WHEN '$Racial_Group' = 'White' THEN Deaths_White\r\n      WHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\n      WHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\n      WHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\n      WHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\n    END\r\n  ) as Deaths\r\nFROM\r\n  COVID_Deaths_By_Race\r\nWHERE\r\n  (\r\n    CASE\r\n      WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n      and Date < '2020-11-01'\r\n      WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n      and Date < '2021-06-01'\r\n      WHEn '$Variant' = 'Delta' THEN Date >= '2021-06-01'\r\n      and Date < '2021-11-01'\r\n    END\r\n  )\r\nORDER BY\r\n  Deaths DESC\r\nLIMIT\r\n  1"
    },
    {
     "rawSql": "SELECT\r\n  SUM(\r\n    (\r\n      CASE\r\n        WHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\n        WHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\n        WHEN '$Racial_Group' = 'White' THEN Cases_White\r\n        WHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\n        WHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\n        WHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\n        WHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\n      END\r\n    )\r\n  ) as Cases\r\nFROM\r\n  COVID_Cases_By_Race\r\nWHERE\r\n(\r\n    CASE\r\n      WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n      and Date < '2020-11-01'\r\n      WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n      and Date < '2021-06-01'\r\n      WHEn '$Variant' = 'Delta' THEN Date >= '2021-06-01'\r\n      and Date < '2021-11-01'\r\n    END\r\n  ) ORDER BY Cases DESC LIMIT 1"
    },
    {
     "rawSql": "SELECT\r\n  SUM(\r\n    (\r\n      CASE\r\n        WHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\n        WHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\n        WHEN '$Racial_Group' = 'White' THEN Hosp_White\r\n        WHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\n        WHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\n        WHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\n        WHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\n      END\r\n    )\r\n  ) as Hospitalizations\r\nFROM\r\n  COVID_Hospitalizations_By_Race\r\nWHERE\r\n(\r\n    CASE\r\n      WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n      and Date < '2020-11-01'\r\n      WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n      and Date < '2021-06-01'      \r\n      WHEn '$Variant' = 'Delta' THEN Date >= '2021-06-01'\r\n      and Date < '2021-11-01'\r\n    END\r\n  ) ORDER BY Hospitalizations DESC LIMIT 1"
    }
   ]
  },
  {
   "title": "General Delta Type Variant Peak Statistics ",
   "type": "stat",
   "description": "Peak statistics, the most of any quantity on a day. ",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Total_Deaths as Peak_Deaths FROM DeathsDelta LIMIT 1"
    },
    {
     "rawSql": "SELECT mx as Peak_Cases FROM MaxCaseDelta LIMIT 1"
    },
    {
     "rawSql": "SELECT Date,Hosp_Total as Peak_Hospitalizations FROM HospDelta LIMIT 1"
    }
   ]
  },
  {
   "title": "General Omicron Type Variant Peak Statistics ",
   "type": "stat",
   "description": "Peak statistics, the most of any quantity on a day. ",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 3 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT Total_Deaths as Peak_Deaths FROM DeathsOmicron LIMIT 1"
    },
    {
     "rawSql": "SELECT mx as Peak_Cases FROM MaxCaseOmicron LIMIT 1"
    },
    {
     "rawSql": "SELECT Date,Hosp_Total as Peak_Hospitalizations FROM HospOmicron LIMIT 1"
    }
   ]
  },
  {
   "title": "Statistics for $Variant Variant for $Racial_Group Populations ",
   "type": "timeseries",
   "description": "Peak statistics, the most of any quantity on a day for a given race and variant. ",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\n      WHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\n      WHEN '$Racial_Group' = 'White' THEN Deaths_White\r\n      WHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\n      WHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\n      WHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\n      WHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\n    END\r\n  ) as Total_Deaths\r\nFROM\r\n  COVID_Deaths_By_Race\r\nWHERE\r\n  (\r\n    CASE\r\n      WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n      and Date < '2020-11-01'\r\n      WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n      and Date < '2021-06-01'\r\n      WHEn '$Variant' = 'Delta' THEN Date >= '2021-06-01'\r\n      and Date < '2021-11-01'\r\n    END\r\n  )"
    },
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\n      WHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\n      WHEN '$Racial_Group' = 'White' THEN Cases_White\r\n      WHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\n      WHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\n      WHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\n      WHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\n    END\r\n  ) as Total_Cases\r\nFROM\r\n  COVID_Cases_By_Race\r\nWHERE\r\n  (\r\n    CASE\r\n      WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n      and Date < '2020-11-01'\r\n      WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n      and Date < '2021-06-01'\r\n      WHEn '$Variant' = 'Delta' THEN Date >= '2021-06-01'\r\n      and Date < '2021-11-01'\r\n    END\r\n  )"
    },
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\n      WHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\n      WHEN '$Racial_Group' = 'White' THEN Hosp_White\r\n      WHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\n      WHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\n      WHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\n      WHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\n    END\r\n  ) as Total_Hosp\r\nFROM\r\n  COVID_Hospitalizations_By_Race\r\nWHERE\r\n  (\r\n    CASE\r\n      WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n      and Date < '2020-11-01'\r\n      WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n      and Date < '2021-06-01'\r\n      WHEn '$Variant' = 'Delta' THEN Date >= '2021-06-01'\r\n      and Date < '2021-11-01'\r\n    END\r\n  )"
    }
   ]
  },
  {
   "title": "Cases, Tests, and Deaths For $Racial_Group Populations Nationally",
   "type": "timeseries",
   "description": "National Trends of Cases, Deaths, and Tests",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 7 },
   "targets": [
    {
     "rawSql": "SELECT \r\nDate, \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND)) as Total_Cases\r\nFROM COVID_Cases_By_Race GROUP BY Date"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Tests_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Tests_Black\r\nWHEN '$Racial_Group' = 'White' THEN Tests_White\r\nWHEN '$Racial_Group' = 'Total' THEN Tests_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Tests_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Tests_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Tests_NHPI\r\nEND)) as Total_Tests\r\nFROM COVID_Test_By_Race GROUP BY Date"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND)) as Total_Deaths\r\nFROM COVID_Deaths_By_Race GROUP BY Date"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\nSUM((CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND)) as Total_Hospitalizations\r\nFROM COVID_Hospitalizations_By_Race GROUP BY Date"
    }
   ]
  },
  {
   "title": "State Population By Selected Racial Group",
   "type": "marcusolsson-treemap-panel",
   "gridPos": { "h": 11, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "\r\n\r\nSELECT \r\nState, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN AsianTotal\r\nWHEN '$Racial_Group' = 'Black' THEN BlackTotal\r\nWHEN '$Racial_Group' = 'White' THEN WhiteTotal\r\nWHEN '$Racial_Group' = 'Latinx' THEN OtherTotal\r\nWHEN '$Racial_Group' = 'AIAN' THEN HawaiianTotal\r\nWHEN '$Racial_Group' = 'NHPI' THEN IndianTotal\r\nEND) as Population_Percentage\r\nFROM US_Population_Racial"
    }
   ]
  },
  {
   "title": "Political Composition Per State",
   "type": "geomap",
   "description": "Numerical Values Represent Republicans, Democrats, and Independents in that order. Units are in percentages. \n",
   "gridPos": { "h": 11, "w": 12, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT State_Name, Republican_lean_rep,No_Lean, Democrat_Lean_Dem,longitude,latitude FROM \r\nState_Political_Composition NATURAL JOIN State_Locations"
    }
   ]
  },
  { "title": "Maps", "type": "dashlist", "gridPos": { "h": 11, "w": 6, "x": 18, "y": 15 } }
 ]
}