{
 "title": "State COVID And Patient Outcomes By Race",
 "description": "Presentation of COVID19 and its Effects on Outcomes",
 "time": { "from": "2020-04-12T00:00:00.000Z", "to": "2021-03-07T00:00:00.000Z" },
 "templating": {
  "list": [
   { "name": "Racial_Group", "query": "SELECT * FROM Racial_Category" },
   {
    "name": "States",
    "query": "SELECT State_Name FROM State_To_Code"
   }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<h1 style=\"text-align: center;\">Racial Trends per State</h1>\n\n"
   }
  },
  {
   "title": "Cases, Tests, Hospitalizations, and Deaths Per Race Per State",
   "type": "timeseries",
   "description": "Analysis between the number of cases, number of tests, and number of deaths for a given state and race. \n",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 2 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND) as Total_Cases\r\nFROM (SELECT * FROM COVID_Cases_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Tests_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Tests_Black\r\nWHEN '$Racial_Group' = 'Total' THEN Tests_Total\r\nWHEN '$Racial_Group' = 'White' THEN Tests_White\r\nWHEN '$Racial_Group' = 'Latinx' THEN Tests_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Tests_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Tests_NHPI\r\nEND) as Total_Tests\r\nFROM (SELECT * FROM COVID_Test_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND) as Total_Deaths\r\nFROM (SELECT * FROM COVID_Deaths_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Total_Hospitalizations\r\nFROM (SELECT * FROM COVID_Hospitalizations_By_With_State_Name WHERE State_Name = '$States') as b"
    }
   ]
  },
  {
   "title": "Cases, Tests, Hospitalizations, and Deaths Per Race Per State",
   "type": "status-history",
   "description": "Analysis between the number of cases, number of tests, and number of deaths for a given state and race. \n",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND) as Total_Cases\r\nFROM (SELECT * FROM COVID_Cases_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Tests_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Tests_Black\r\nWHEN '$Racial_Group' = 'Total' THEN Tests_Total\r\nWHEN '$Racial_Group' = 'White' THEN Tests_White\r\nWHEN '$Racial_Group' = 'Latinx' THEN Tests_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Tests_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Tests_NHPI\r\nEND) as Total_Tests\r\nFROM (SELECT * FROM COVID_Test_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND) as Total_Deaths\r\nFROM (SELECT * FROM COVID_Deaths_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Total_Hospitalizations\r\nFROM (SELECT * FROM COVID_Hospitalizations_By_With_State_Name WHERE State_Name = '$States') as b"
    }
   ]
  },
  {
   "title": "Demographic Percentage Breakdown",
   "type": "piechart",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM  US_Population_Racial_Percentages WHERE '$States' = State"
    }
   ]
  },
  {
   "title": "WIld Variant Peak Statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nDate,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Hospitalizations \r\nFROM (\r\nSELECT \r\n*\r\nFROM COVID_Hospitalizations_By_Race JOIN State_To_Code ON\r\nCOVID_Hospitalizations_By_Race.State = State_To_Code.code WHERE Date >= '2020-01-01' and Date < '2020-11-01' AND State_Name = '$States' GROUP BY State\r\nORDER BY Hosp_Total DESC LIMIT 1\r\n) as b"
    }
   ]
  },
  {
   "title": "Alpha Variant Peak Statistics",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nDate,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Hospitalizations \r\nFROM (\r\nSELECT \r\n*\r\nFROM COVID_Hospitalizations_By_Race JOIN State_To_Code ON\r\nCOVID_Hospitalizations_By_Race.State = State_To_Code.code  WHERE Date >= '2020-11-01' and Date < '2021-06-01' AND State_Name = '$States' GROUP BY State\r\nORDER BY Hosp_Total DESC LIMIT 1\r\n) as b"
    }
   ]
  },
  {
   "title": "Racial Comparison of Cases Cumulative",
   "type": "stat",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT \r\nState_Name,\r\nSUM(Cases_Asian) AS Asian_Total,\r\nSUM(Cases_Black) AS Black_Total,\r\nSUM(Cases_White) AS White_Total,\r\nSUM(Cases_Total) AS Total,\r\nSUM(Cases_Latinx) AS LatinX_Total,\r\nSUM(Cases_AIAN) AS AIAN_Total,\r\nSUM(Cases_NHPI) AS NHPI_Total\r\n\r\nFROM COVID_Cases_By_Race JOIN State_To_Code ON\r\nCOVID_Cases_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name ) as raw WHERE '$States' = State_Name"
    }
   ]
  },
  {
   "title": "Racial Comparison of Deaths Cumulative",
   "type": "stat",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT \r\nState_Name,\r\nSUM(Deaths_Asian) AS Asian_Total,\r\nSUM(Deaths_Black) AS Black_Total,\r\nSUM(Deaths_White) AS White_Total,\r\nSUM(Deaths_Total) AS Total,\r\nSUM(Deaths_Latinx) AS LatinX_Total,\r\nSUM(Deaths_AIAN) AS AIAN_Total,\r\nSUM(Deaths_NHPI) AS NHPI_Total\r\n\r\nFROM COVID_Deaths_By_Race JOIN State_To_Code ON\r\nCOVID_Deaths_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name ) as raw WHERE '$States' = State_Name"
    }
   ]
  },
  {
   "title": "WIld Variant Peak Statistics",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nDate,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND) as Deaths\r\nFROM (\r\nSELECT \r\n*\r\nFROM COVID_Deaths_By_Race JOIN State_To_Code ON\r\nCOVID_Deaths_By_Race.State = State_To_Code.code WHERE Date >= '2020-01-01' and Date < '2020-11-01' AND State_Name = '$States' GROUP BY State\r\nORDER BY Deaths_Total DESC LIMIT 1\r\n) as b "
    },
    {
     "rawSql": "SELECT \r\nDate,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND) as Cases \r\nFROM (\r\nSELECT \r\n*\r\nFROM COVID_Cases_By_Race JOIN State_To_Code ON\r\nCOVID_Cases_By_Race.State = State_To_Code.code WHERE Date >= '2020-01-01' and Date < '2020-11-01' AND State_Name = '$States' GROUP BY State\r\nORDER BY Cases_Total DESC LIMIT 1\r\n) as b"
    },
    {
     "rawSql": "SELECT \r\nDate,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Hospitalizations \r\nFROM (\r\nSELECT \r\n*\r\nFROM COVID_Hospitalizations_By_Race JOIN State_To_Code ON\r\nCOVID_Hospitalizations_By_Race.State = State_To_Code.code WHERE Date >= '2020-01-01' and Date < '2020-11-01' AND State_Name = '$States' GROUP BY State\r\nORDER BY Hosp_Total DESC LIMIT 1\r\n) as b"
    }
   ]
  },
  {
   "title": "Alpha Variant Peak Statistics",
   "type": "stat",
   "gridPos": { "h": 13, "w": 6, "x": 6, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \r\nDate,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND) as Deaths\r\nFROM (\r\nSELECT \r\n*\r\nFROM COVID_Deaths_By_Race JOIN State_To_Code ON\r\nCOVID_Deaths_By_Race.State = State_To_Code.code  WHERE Date >= '2020-11-01' and Date < '2021-06-01'AND State_Name = '$States' GROUP BY State\r\nORDER BY Deaths_Total DESC LIMIT 1\r\n) as b "
    },
    {
     "rawSql": "SELECT \r\nDate,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND) as Cases \r\nFROM (\r\nSELECT \r\n*\r\nFROM COVID_Cases_By_Race JOIN State_To_Code ON\r\nCOVID_Cases_By_Race.State = State_To_Code.code WHERE Date >= '2020-11-01' and Date < '2021-06-01' AND State_Name = '$States' GROUP BY State\r\nORDER BY Cases_Total DESC LIMIT 1\r\n) as b"
    },
    {
     "rawSql": "SELECT \r\nDate,\r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Hospitalizations \r\nFROM (\r\nSELECT \r\n*\r\nFROM COVID_Hospitalizations_By_Race JOIN State_To_Code ON\r\nCOVID_Hospitalizations_By_Race.State = State_To_Code.code  WHERE Date >= '2020-11-01' and Date < '2021-06-01' AND State_Name = '$States' GROUP BY State\r\nORDER BY Hosp_Total DESC LIMIT 1\r\n) as b"
    }
   ]
  }
 ]
}