{
 "title": "State COVID And Patient Outcomes By Race - Republican Learning",
 "description": "Presentation of COVID19 and its Effects on Outcomes ",
 "tags": [
  "JHU-315",
  "Health",
  "Politics",
  "Race",
  "State"
 ],
 "time": { "from": "2020-04-12T00:00:00.000Z", "to": "2021-03-07T00:00:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "Racial_Group",
    "query": "Total,White,Black,Latinx,Asian,AIAN,NHPI"
   },
   {
    "name": "States",
    "query": "SELECT State_Name FROM Republican_States\n"
   },
   { "name": "Variant", "query": "Wild Type, Alpha" }
  ]
 },
 "panels": [
  {
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "options": {
    "content": "\n<h1 style=\"text-align: center;\">COVID Racial Analysis For $States </h1>\n<div style=\"text-align: center;\">With Focus On ${Racial_Group} Populations</div>\n"
   }
  },
  {
   "title": "Cases, Tests, Hospitalizations, and Deaths For $Racial_Group Populations",
   "type": "timeseries",
   "description": "Analysis between the number of cases, number of tests, and number of deaths for a given state and race. \n",
   "gridPos": { "h": 12, "w": 24, "x": 0, "y": 3 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND) as Total_Cases\r\nFROM (SELECT * FROM COVID_Cases_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Tests_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Tests_Black\r\nWHEN '$Racial_Group' = 'Total' THEN Tests_Total\r\nWHEN '$Racial_Group' = 'White' THEN Tests_White\r\nWHEN '$Racial_Group' = 'Latinx' THEN Tests_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Tests_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Tests_NHPI\r\nEND) as Total_Tests\r\nFROM (SELECT * FROM COVID_Test_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND) as Total_Deaths\r\nFROM (SELECT * FROM COVID_Deaths_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Total_Hospitalizations\r\nFROM (SELECT * FROM COVID_Hospitalizations_By_With_State_Name WHERE State_Name = '$States') as b"
    }
   ]
  },
  {
   "title": "Cases, Tests, Hospitalizations, and Deaths for $Racial_Group",
   "type": "status-history",
   "description": "Analysis between the number of cases, number of tests, and number of deaths for a given state and race. \n",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 15 },
   "targets": [
    {
     "dataset": "jhu_315_final_project",
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\nWHEN '$Racial_Group' = 'White' THEN Cases_White\r\nWHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\nEND) as Total_Cases\r\nFROM (SELECT * FROM COVID_Cases_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Tests_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Tests_Black\r\nWHEN '$Racial_Group' = 'Total' THEN Tests_Total\r\nWHEN '$Racial_Group' = 'White' THEN Tests_White\r\nWHEN '$Racial_Group' = 'Latinx' THEN Tests_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Tests_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Tests_NHPI\r\nEND) as Total_Tests\r\nFROM (SELECT * FROM COVID_Test_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\nWHEN '$Racial_Group' = 'White' THEN Deaths_White\r\nWHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\nEND) as Total_Deaths\r\nFROM (SELECT * FROM COVID_Deaths_By_With_State_Name WHERE State_Name = '$States') as b"
    },
    {
     "rawSql": "SELECT \r\nDate, \r\n(CASE \r\nWHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\nWHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\nWHEN '$Racial_Group' = 'White' THEN Hosp_White\r\nWHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\nWHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\nWHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\nWHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\nEND) as Total_Hospitalizations\r\nFROM (SELECT * FROM COVID_Hospitalizations_By_With_State_Name WHERE State_Name = '$States') as b"
    }
   ]
  },
  {
   "title": "$States Demographic Breakdown ",
   "type": "piechart",
   "description": "Percentage of each racial population within the given state.",
   "gridPos": { "h": 11, "w": 6, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT * FROM  US_Population_Racial_Percentages WHERE '$States' = State"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT $Racial_Group/100 As 'Percentage of Democrats that Identify as $Racial_Group' FROM State_Political_Composition_By_Race WHERE '$States'  = State_Name"
    }
   ]
  },
  {
   "title": "Population Political Composition ",
   "type": "stat",
   "description": "Percentages of republicans and democrats in the state",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Republican_lean_rep,\r\n  Democrat_lean_Dem\r\nFROM\r\n  State_Political_Composition\r\nWHERE\r\n  State_Name = \"$States\""
    }
   ]
  },
  {
   "title": "$Variant Peak Statistics - Date",
   "type": "stat",
   "gridPos": { "h": 3, "w": 12, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "dateTimeAsIso" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\n      WHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\n      WHEN '$Racial_Group' = 'White' THEN Cases_White\r\n      WHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\n      WHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\n      WHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\n      WHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\n    END\r\n  ) as Cases\r\nFROM\r\n  (\r\n    SELECT\r\n      *\r\n    FROM\r\n      COVID_Cases_By_Race\r\n      JOIN State_To_Code ON COVID_Cases_By_Race.State = State_To_Code.code\r\nWHERE\r\n      (\r\n        CASE\r\n          WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n          and Date < '2020-11-01'\r\n          WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n          and Date < '2021-06-01'\r\n        END\r\n      )\r\n      AND State_Name = '$States'\r\n    GROUP BY\r\n      State\r\n    ORDER BY\r\n      Cases_Total DESC\r\n    LIMIT\r\n      1\r\n  ) as b"
    }
   ]
  },
  {
   "title": "Racial Comparison of Cases Cumulative",
   "type": "stat",
   "gridPos": { "h": 17, "w": 6, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT \r\nState_Name,\r\nSUM(Cases_Asian) AS Asian_Total,\r\nSUM(Cases_Black) AS Black_Total,\r\nSUM(Cases_White) AS White_Total,\r\nSUM(Cases_Total) AS Total,\r\nSUM(Cases_Latinx) AS LatinX_Total,\r\nSUM(Cases_AIAN) AS AIAN_Total,\r\nSUM(Cases_NHPI) AS NHPI_Total\r\n\r\nFROM COVID_Cases_By_Race JOIN State_To_Code ON\r\nCOVID_Cases_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name ) as raw WHERE '$States' = State_Name"
    }
   ]
  },
  {
   "title": "Racial Comparison of Deaths Cumulative",
   "type": "stat",
   "gridPos": { "h": 17, "w": 6, "x": 18, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT * FROM (\r\nSELECT \r\nState_Name,\r\nSUM(Deaths_Asian) AS Asian_Total,\r\nSUM(Deaths_Black) AS Black_Total,\r\nSUM(Deaths_White) AS White_Total,\r\nSUM(Deaths_Total) AS Total,\r\nSUM(Deaths_Latinx) AS LatinX_Total,\r\nSUM(Deaths_AIAN) AS AIAN_Total,\r\nSUM(Deaths_NHPI) AS NHPI_Total\r\n\r\nFROM COVID_Deaths_By_Race JOIN State_To_Code ON\r\nCOVID_Deaths_By_Race.State = State_To_Code.code\r\nGROUP BY State_To_Code.State_Name ) as raw WHERE '$States' = State_Name"
    }
   ]
  },
  {
   "title": "$Variant Type Peak Statistics for $Racial_Group",
   "type": "stat",
   "gridPos": { "h": 14, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Racial_Group' = 'Asian' THEN Deaths_Asian\r\n      WHEN '$Racial_Group' = 'Black' THEN Deaths_Black\r\n      WHEN '$Racial_Group' = 'White' THEN Deaths_White\r\n      WHEN '$Racial_Group' = 'Total' THEN Deaths_Total\r\n      WHEN '$Racial_Group' = 'Latinx' THEN Deaths_Latinx\r\n      WHEN '$Racial_Group' = 'AIAN' THEN Deaths_AIAN\r\n      WHEN '$Racial_Group' = 'NHPI' THEN Deaths_NHPI\r\n    END\r\n  ) as Deaths\r\nFROM\r\n  (\r\n    SELECT\r\n      *\r\n    FROM\r\n      COVID_Deaths_By_Race\r\n      JOIN State_To_Code ON COVID_Deaths_By_Race.State = State_To_Code.code\r\n    WHERE\r\n      (\r\n        CASE\r\n          WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n          and Date < '2020-11-01'\r\n          WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n          and Date < '2021-06-01'\r\n        END\r\n      )\r\n      AND State_Name = '$States'\r\n    GROUP BY\r\n      State\r\n    ORDER BY\r\n      Deaths_Total DESC\r\n    LIMIT\r\n      1\r\n  ) as b"
    },
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Racial_Group' = 'Asian' THEN Cases_Asian\r\n      WHEN '$Racial_Group' = 'Black' THEN Cases_Black\r\n      WHEN '$Racial_Group' = 'White' THEN Cases_White\r\n      WHEN '$Racial_Group' = 'Total' THEN Cases_Total\r\n      WHEN '$Racial_Group' = 'Latinx' THEN Cases_Latinx\r\n      WHEN '$Racial_Group' = 'AIAN' THEN Cases_AIAN\r\n      WHEN '$Racial_Group' = 'NHPI' THEN Cases_NHPI\r\n    END\r\n  ) as Cases\r\nFROM\r\n  (\r\n    SELECT\r\n      *\r\n    FROM\r\n      COVID_Cases_By_Race\r\n      JOIN State_To_Code ON COVID_Cases_By_Race.State = State_To_Code.code\r\n    WHERE\r\n      (\r\n        CASE\r\n          WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n          and Date < '2020-11-01'\r\n          WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n          and Date < '2021-06-01'\r\n        END\r\n      )\r\n    GROUP BY\r\n      State\r\n    ORDER BY\r\n      Cases_Total DESC\r\n    LIMIT\r\n      1\r\n  ) as b"
    },
    {
     "rawSql": "SELECT\r\n  Date,\r\n  (\r\n    CASE\r\n      WHEN '$Racial_Group' = 'Asian' THEN Hosp_Asian\r\n      WHEN '$Racial_Group' = 'Black' THEN Hosp_Black\r\n      WHEN '$Racial_Group' = 'White' THEN Hosp_White\r\n      WHEN '$Racial_Group' = 'Total' THEN Hosp_Total\r\n      WHEN '$Racial_Group' = 'Latinx' THEN Hosp_Latinx\r\n      WHEN '$Racial_Group' = 'AIAN' THEN Hosp_AIAN\r\n      WHEN '$Racial_Group' = 'NHPI' THEN Hosp_NHPI\r\n    END\r\n  ) as Hospitalizations\r\nFROM\r\n  (\r\n    SELECT\r\n      *\r\n    FROM\r\n      COVID_Hospitalizations_By_Race\r\n      JOIN State_To_Code ON COVID_Hospitalizations_By_Race.State = State_To_Code.code\r\nWHERE\r\n      (\r\n        CASE\r\n          WHEN '$Variant' = 'Wild Type' THEN Date >= '2020-01-01'\r\n          and Date < '2020-11-01'\r\n          WHEN '$Variant' = 'Alpha' THEN Date >= '2020-11-01'\r\n          and Date < '2021-06-01'\r\n        END\r\n      )\r\n    GROUP BY\r\n      State\r\n    ORDER BY\r\n      Hosp_Total DESC\r\n    LIMIT\r\n      1\r\n  ) as b"
    }
   ]
  }
 ]
}